name: ConstrukterLobby
version: '${project.version}'
main: de.construkter.construkterlobby.ConstrukterLobby
api-version: '1.20'

commands:
  coins:
    description: Schaue nach, wie viele Coins du besitzt!

  addpremium:
    description: Admin only, Gebe einem Nutzer den Premium Rang

  premium:
    description: Überprüfe ob du Premium hast

  addcoins:
    description: Gebe einem Spieler Coins

  setcoins:
    description: Setze die Coins Anzahl eines bestimmten Spielers

  hilfe:
    description: Zeigt dir eine Liste mit allen Commands